name: dear_diary_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: 
  hive_flutter:
  google_fonts:
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_ui_auth: ^1.9.1
  cloud_firestore: ^4.12.2
  fl_chart: ^0.40.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
