// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcMbFv24KX4DiHMVDhwIMTFHaB324ZP8',
    appId: '1:514543624727:web:112b22b69cd9ae13c57252',
    messagingSenderId: '514543624727',
    projectId: 'dear-diary-app-d9cda',
    authDomain: 'dear-diary-app-d9cda.firebaseapp.com',
    storageBucket: 'dear-diary-app-d9cda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOywzusQRZ5-siF9ASmUXtckVCF8NE7c',
    appId: '1:514543624727:android:051f4c4772ea3d53c57252',
    messagingSenderId: '514543624727',
    projectId: 'dear-diary-app-d9cda',
    storageBucket: 'dear-diary-app-d9cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6XcbtI62zIWxLbje_P_SozRwxZ2eka4',
    appId: '1:514543624727:ios:78f032906c35cd6dc57252',
    messagingSenderId: '514543624727',
    projectId: 'dear-diary-app-d9cda',
    storageBucket: 'dear-diary-app-d9cda.appspot.com',
    iosBundleId: 'com.example.dearDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy6XcbtI62zIWxLbje_P_SozRwxZ2eka4',
    appId: '1:514543624727:ios:bd02047fbacd568bc57252',
    messagingSenderId: '514543624727',
    projectId: 'dear-diary-app-d9cda',
    storageBucket: 'dear-diary-app-d9cda.appspot.com',
    iosBundleId: 'com.example.dearDiaryApp.RunnerTests',
  );
}
